version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aikocute
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: aikocute

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: aikocute
    command: >
      bash -c "
      echo 'php_value upload_max_filesize 60M' >> /var/www/html/.htaccess;
      echo 'php_value post_max_size 60M' >> /var/www/html/.htaccess;
      docker-entrypoint.sh apache2-foreground"
      
volumes:
  db_data:
  wordpress_data:
