version: '3.1'

services:
  wordpress:
    image: wordpress:6.2.2-php8.2-fpm
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    command: >
      bash -c "
      echo 'php_value upload_max_filesize 60M' >> /var/www/html/.htaccess;
      echo 'php_value post_max_size 60M' >> /var/www/html/.htaccess;
      docker-entrypoint.sh apache2-foreground"

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
